spring:
  application:
    name: spring-azure-storage
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
        registration:
          azure-dev:
            redirect-uri: http://localhost:8080/login/oauth2/code/
            provider: azure
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile

app:
  config:
    azure:
      client-id: ${AZURE_CLIENT_ID}
      client-secret: ${AZURE_CLIENT_SECRET}
      tenant-id: ${AZURE_TENANT_ID}
      storage-id: ${AZURE_STORAGE_ID}
      storage-endpoint: ${AZURE_STORAGE_ENDPOINT}
      storage:
        container: ${AZURE_STORAGE_CONTAINER}
